/* ============================================================
   Tracer — Price Checker
   Static PWA. No build step, no dependencies.

   Price history here is generated by a deterministic model so the
   app is fully functional offline and demoable without API keys.
   To go live, replace `getPriceHistory()` with a real fetch to a
   retail price API — the rest of the UI is data-shape agnostic.
   ============================================================ */

(() => {
  "use strict";

  const $ = (sel, root = document) => root.querySelector(sel);
  const fmt = new Intl.NumberFormat(undefined, {
    style: "currency", currency: "USD", maximumFractionDigits: 2,
  });
  const fmt0 = new Intl.NumberFormat(undefined, {
    style: "currency", currency: "USD", maximumFractionDigits: 0,
  });
  const DAY = 86400000;

  /* ---------------- Theme ---------------- */
  const themeBtn = $("#themeToggle");
  const savedTheme = localStorage.getItem("tracer-theme");
  if (savedTheme) {
    document.body.dataset.theme = savedTheme;
  } else if (window.matchMedia("(prefers-color-scheme: light)").matches) {
    document.body.dataset.theme = "light";
  }
  themeBtn.addEventListener("click", () => {
    const next = document.body.dataset.theme === "light" ? "dark" : "light";
    document.body.dataset.theme = next;
    localStorage.setItem("tracer-theme", next);
  });

  /* ---------------- Deterministic model ---------------- */
  // Same item → same history, every time (feels persistent / real).
  function hashStr(s) {
    let h = 2166136261 >>> 0;
    for (let i = 0; i < s.length; i++) {
      h ^= s.charCodeAt(i);
      h = Math.imul(h, 16777619);
    }
    return h >>> 0;
  }
  function mulberry32(seed) {
    let a = seed >>> 0;
    return () => {
      a |= 0; a = (a + 0x6d2b79f5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  // A few recognizable items get realistic anchors; everything else is
  // derived from the query hash so any input returns a sensible price.
  const KNOWN = [
    [/airpods?\s*pro/i, 249, "Audio"],
    [/airpods?\s*max/i, 549, "Audio"],
    [/airpods?/i, 129, "Audio"],
    [/iphone\s*15\s*pro/i, 999, "Phones"],
    [/iphone\s*15/i, 799, "Phones"],
    [/iphone/i, 699, "Phones"],
    [/ipad\s*pro/i, 999, "Tablets"],
    [/ipad/i, 449, "Tablets"],
    [/macbook\s*air/i, 1099, "Laptops"],
    [/macbook\s*pro/i, 1599, "Laptops"],
    [/macbook/i, 1199, "Laptops"],
    [/apple\s*watch|watch\s*ultra/i, 399, "Wearables"],
    [/playstation|ps5/i, 499, "Gaming"],
    [/xbox/i, 499, "Gaming"],
    [/nintendo|switch/i, 299, "Gaming"],
    [/sony\s*wh|headphones?|xm5|xm4/i, 349, "Audio"],
    [/kindle/i, 139, "E-readers"],
    [/dyson/i, 429, "Home"],
    [/nike|adidas|sneakers?|shoes?/i, 119, "Apparel"],
    [/tv|oled|qled/i, 899, "TVs"],
    [/coffee|espresso/i, 199, "Home"],
    [/monitor/i, 329, "Displays"],
    [/keyboard/i, 99, "Accessories"],
    [/camera|gopro/i, 449, "Cameras"],
    [/drone/i, 759, "Cameras"],
    [/laptop/i, 899, "Laptops"],
    [/vacuum/i, 299, "Home"],
  ];

  function basePriceFor(query, rnd) {
    for (const [re, price, cat] of KNOWN) {
      if (re.test(query)) return { base: price, category: cat };
    }
    // hash-derived but plausible: $20 – $900 on a log-ish curve
    const t = rnd();
    const base = Math.round((20 + Math.pow(t, 1.7) * 880) / 5) * 5 - 0.01;
    return { base, category: "Product" };
  }

  // Seasonal sale calendar — fraction-of-day-in-year → discount depth.
  // Each event: [month(0-11), day, depth(0-1), spread(days)]
  const EVENTS = [
    [10, 28, 0.18, 9],  // Black Friday
    [11, 1, 0.16, 6],   // Cyber Monday window
    [11, 26, 0.14, 7],  // Boxing week
    [6, 12, 0.15, 6],   // Prime Day (mid-July)
    [7, 25, 0.10, 12],  // Back to school
    [4, 26, 0.09, 6],   // Memorial Day
    [8, 4, 0.08, 5],    // Labor Day
    [1, 12, 0.07, 6],   // Presidents' / Valentine
  ];

  function seasonalDiscount(date) {
    let d = 0;
    const y = date.getFullYear();
    for (const [mo, day, depth, spread] of EVENTS) {
      const ev = new Date(y, mo, day).getTime();
      const dist = Math.abs(date.getTime() - ev) / DAY;
      if (dist < spread * 2.2) {
        d = Math.max(d, depth * Math.exp(-(dist * dist) / (2 * spread * spread)));
      }
    }
    return d;
  }

  function getPriceHistory(query) {
    const key = query.trim().toLowerCase();
    const seed = hashStr(key || "tracer");
    const rnd = mulberry32(seed);
    const { base, category } = basePriceFor(key, rnd);

    const days = 365;
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const start = today.getTime() - (days - 1) * DAY;

    // gentle product life-cycle drift (some go up, most drift down)
    const drift = (rnd() - 0.62) * 0.16;       // net % change across the year
    const volatility = 0.012 + rnd() * 0.02;   // daily noise scale
    let walk = 0;

    const series = [];
    for (let i = 0; i < days; i++) {
      const date = new Date(start + i * DAY);
      const progress = i / (days - 1);
      // random walk that mean-reverts so it never wanders off
      walk = walk * 0.86 + (rnd() - 0.5) * volatility;
      const trend = 1 + drift * progress;
      const wobble = 1 + Math.sin(progress * Math.PI * 3 + seed % 7) * 0.02;
      const sale = 1 - seasonalDiscount(date);
      let price = base * trend * wobble * (1 + walk) * sale;
      // occasional flash dip
      if (rnd() > 0.985) price *= 0.93;
      price = Math.max(base * 0.45, price);
      series.push({ t: date.getTime(), price: Math.round(price * 100) / 100 });
    }
    return { series, category, base };
  }

  /* ---------------- Stats + verdict ---------------- */
  function computeStats(series) {
    let lo = series[0], hi = series[0], sum = 0;
    for (const p of series) {
      if (p.price < lo.price) lo = p;
      if (p.price > hi.price) hi = p;
      sum += p.price;
    }
    const avg = sum / series.length;
    const current = series[series.length - 1];
    const prior = series[Math.max(0, series.length - 8)]; // ~1 week ago
    const span = Math.max(0.01, hi.price - lo.price);
    const position = (current.price - lo.price) / span; // 0 = at the low
    const weekDelta = (current.price - prior.price) / prior.price;
    const offHigh = (hi.price - current.price) / hi.price;
    return { lo, hi, avg, current, position, weekDelta, offHigh };
  }

  function verdictFor(s) {
    if (s.current.price <= s.lo.price * 1.02 || s.position < 0.16) {
      return { cls: "buy", label: "Buy now — near its lowest",
        line: `This is within <strong>${pct(s.position)}</strong> of the cheapest it's been all year. Strong time to buy.` };
    }
    if (s.position < 0.5) {
      return { cls: "fair", label: "Fair price",
        line: `A reasonable price, but it's dropped to <strong>${fmt.format(s.lo.price)}</strong> before. You could save by waiting for a sale.` };
    }
    return { cls: "wait", label: "Hold off if you can",
      line: `Currently priced high for the year — about <strong>${pct((s.current.price - s.lo.price) / s.lo.price)}</strong> above its yearly low of <strong>${fmt.format(s.lo.price)}</strong>.` };
  }

  function nextSaleHint(fromDate) {
    const names = ["New Year sales", "Presidents' Day", "spring sales", "Memorial Day",
      "early-summer sales", "Prime Day", "back-to-school sales", "Labor Day",
      "fall sales", "Black Friday", "Black Friday", "Boxing Week"];
    let best = null;
    for (const [mo, day] of EVENTS) {
      for (const yr of [fromDate.getFullYear(), fromDate.getFullYear() + 1]) {
        const ev = new Date(yr, mo, day);
        if (ev > fromDate) {
          const days = Math.round((ev - fromDate) / DAY);
          if (!best || days < best.days) best = { days, name: names[mo] || "a seasonal sale", ev };
        }
      }
    }
    return best;
  }

  const pct = (x) => `${Math.round(Math.abs(x) * 100)}%`;

  /* ---------------- Rendering ---------------- */
  const resultEl = $("#result");
  let current = null; // { query, data, stats }
  let activeRange = 365;

  function rangeSlice(series, days) {
    return days >= series.length ? series : series.slice(series.length - days);
  }

  function render(query) {
    const data = getPriceHistory(query);
    current = { query, data };
    activeRange = 365;
    drawResult();
    location.hash = encodeURIComponent(query);
    pushRecent(query);
  }

  function drawResult() {
    const { query, data } = current;
    const series = rangeSlice(data.series, activeRange);
    const s = computeStats(series);
    const v = verdictFor(s);
    const title = query.replace(/\s+/g, " ").trim();

    const loDate = new Date(s.lo.t), hiDate = new Date(s.hi.t);
    const hint = nextSaleHint(new Date());

    resultEl.innerHTML = `
      <div class="card item-head reveal d1">
        <div class="item-id">
          <span class="verdict ${v.cls}"><span class="pulse"></span>${v.label}</span>
          <h2 class="item-name">${escapeHtml(title)}</h2>
          <p class="item-sub">${data.category} · price history over the past year</p>
        </div>
        <div class="price-now">
          <span class="label">Current price</span>
          <span class="val">${fmt.format(s.current.price)}</span>
          <span class="delta ${s.weekDelta >= 0 ? "up" : "down"}">
            ${s.weekDelta >= 0 ? "▲" : "▼"} ${pct(s.weekDelta)} this week
          </span>
        </div>
      </div>

      <div class="stats reveal d2">
        <div class="card stat lo">
          <div class="k">Yearly low</div>
          <div class="v">${fmt.format(s.lo.price)}</div>
          <div class="meta">${dateShort(loDate)}</div>
        </div>
        <div class="card stat hi">
          <div class="k">Yearly high</div>
          <div class="v">${fmt.format(s.hi.price)}</div>
          <div class="meta">${dateShort(hiDate)}</div>
        </div>
        <div class="card stat">
          <div class="k">Average</div>
          <div class="v">${fmt.format(s.avg)}</div>
          <div class="meta">typical price</div>
        </div>
        <div class="card stat">
          <div class="k">Off peak</div>
          <div class="v">${pct(s.offHigh)}</div>
          <div class="meta">below the high</div>
        </div>
      </div>

      <div class="card chart-card reveal d3">
        <div class="chart-head">
          <div class="chart-title">Price history <span>· ${fmt.format(s.lo.price)}–${fmt.format(s.hi.price)}</span></div>
          <div class="range" role="tablist" aria-label="Time range">
            ${[["3M", 90], ["6M", 180], ["1Y", 365]].map(([lbl, d]) =>
              `<button type="button" data-days="${d}" class="${d === activeRange ? "on" : ""}">${lbl}</button>`).join("")}
          </div>
        </div>
        <div class="chart-wrap" id="chartWrap"></div>
      </div>

      <div class="card insight reveal d3">
        <div class="insight-ico">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M12 2v4M12 18v4M2 12h4M18 12h4"/><circle cx="12" cy="12" r="4.5"/>
          </svg>
        </div>
        <p>${v.line}${hint ? ` Next likely dip: <strong>${hint.name}</strong>, in about ${hint.days} days.` : ""}</p>
      </div>
    `;

    resultEl.hidden = false;
    drawChart(series, s);

    // range toggles
    resultEl.querySelectorAll(".range button").forEach((b) =>
      b.addEventListener("click", () => {
        activeRange = +b.dataset.days;
        drawResult();
        resultEl.scrollIntoView({ behavior: "smooth", block: "nearest" });
      }));
  }

  /* ---------------- SVG chart ---------------- */
  function drawChart(series, s) {
    const wrap = $("#chartWrap");
    const W = 760, H = 300;
    const padL = 8, padR = 8, padT = 18, padB = 26;
    const innerW = W - padL - padR, innerH = H - padT - padB;

    const prices = series.map((p) => p.price);
    let min = Math.min(...prices), max = Math.max(...prices);
    const padV = (max - min) * 0.18 || max * 0.1;
    min -= padV; max += padV;

    const X = (i) => padL + (i / (series.length - 1)) * innerW;
    const Y = (v) => padT + (1 - (v - min) / (max - min)) * innerH;

    // smooth path (Catmull-Rom → bezier)
    const pts = series.map((p, i) => [X(i), Y(p.price)]);
    const line = smoothPath(pts);
    const area = `${line} L ${X(series.length - 1)} ${padT + innerH} L ${X(0)} ${padT + innerH} Z`;

    const avgY = Y(s.avg);
    const loI = series.indexOf(s.lo), hiI = series.indexOf(s.hi);

    // y gridlines + labels (3 ticks)
    let grid = "";
    for (let k = 0; k <= 3; k++) {
      const val = min + (max - min) * (k / 3);
      const gy = Y(val);
      grid += `<line class="grid-line" x1="${padL}" y1="${gy.toFixed(1)}" x2="${W - padR}" y2="${gy.toFixed(1)}"/>`;
      grid += `<text class="axis-label" x="${padL + 2}" y="${(gy - 5).toFixed(1)}">${fmt0.format(val)}</text>`;
    }
    // x month labels
    let xlab = "";
    const step = Math.max(1, Math.floor(series.length / 5));
    for (let i = 0; i < series.length; i += step) {
      const d = new Date(series[i].t);
      xlab += `<text class="axis-label" x="${X(i).toFixed(1)}" y="${H - 6}" text-anchor="middle">${d.toLocaleDateString(undefined, { month: "short" })}</text>`;
    }

    wrap.innerHTML = `
      <svg class="chart-svg" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img"
           aria-label="Line chart of price over time">
        <defs>
          <linearGradient id="areaGrad" x1="0" y1="0" x2="0" y2="1">
            <stop offset="0" stop-color="var(--orange)" stop-opacity="0.28"/>
            <stop offset="1" stop-color="var(--orange)" stop-opacity="0"/>
          </linearGradient>
        </defs>
        ${grid}
        <path class="area-fill" d="${area}" fill="url(#areaGrad)"/>
        <line class="avg-line" x1="${padL}" y1="${avgY.toFixed(1)}" x2="${W - padR}" y2="${avgY.toFixed(1)}"/>
        <path class="price-line" d="${line}"/>
        ${xlab}
        <circle class="dot-hi" cx="${X(hiI).toFixed(1)}" cy="${Y(s.hi.price).toFixed(1)}" r="5"/>
        <circle class="dot-lo" cx="${X(loI).toFixed(1)}" cy="${Y(s.lo.price).toFixed(1)}" r="5"/>
        <g id="hoverG" style="opacity:0">
          <line class="hover-line" y1="${padT}" y2="${padT + innerH}"/>
          <circle class="hover-dot" r="5"/>
        </g>
      </svg>`;

    const svg = wrap.querySelector("svg");
    const path = wrap.querySelector(".price-line");
    const len = path.getTotalLength();
    svg.style.setProperty("--len", len);
    wrap.parentElement.classList.add("draw");
    void path.getBoundingClientRect(); // reflow so the animation restarts

    setupHover(wrap, svg, series, X, Y, W, H);
  }

  function smoothPath(pts) {
    if (pts.length < 2) return "";
    let d = `M ${pts[0][0].toFixed(2)} ${pts[0][1].toFixed(2)}`;
    for (let i = 0; i < pts.length - 1; i++) {
      const p0 = pts[i - 1] || pts[i];
      const p1 = pts[i];
      const p2 = pts[i + 1];
      const p3 = pts[i + 2] || p2;
      const c1x = p1[0] + (p2[0] - p0[0]) / 6;
      const c1y = p1[1] + (p2[1] - p0[1]) / 6;
      const c2x = p2[0] - (p3[0] - p1[0]) / 6;
      const c2y = p2[1] - (p3[1] - p1[1]) / 6;
      d += ` C ${c1x.toFixed(2)} ${c1y.toFixed(2)}, ${c2x.toFixed(2)} ${c2y.toFixed(2)}, ${p2[0].toFixed(2)} ${p2[1].toFixed(2)}`;
    }
    return d;
  }

  /* ---------------- Hover / touch tooltip ---------------- */
  const tooltip = $("#tooltip");
  function setupHover(wrap, svg, series, X, Y, W, H) {
    const hoverG = svg.querySelector("#hoverG");
    const hLine = hoverG.querySelector(".hover-line");
    const hDot = hoverG.querySelector(".hover-dot");

    function move(clientX) {
      const rect = svg.getBoundingClientRect();
      const rel = (clientX - rect.left) / rect.width; // 0..1
      let i = Math.round(rel * (series.length - 1));
      i = Math.max(0, Math.min(series.length - 1, i));
      const p = series[i];
      const sx = X(i), sy = Y(p.price);
      hoverG.style.opacity = "1";
      hLine.setAttribute("x1", sx); hLine.setAttribute("x2", sx);
      hDot.setAttribute("cx", sx); hDot.setAttribute("cy", sy);

      // tooltip is fixed-position; map svg coords → screen
      const px = rect.left + (sx / W) * rect.width;
      const py = rect.top + (sy / H) * rect.height;
      tooltip.hidden = false;
      tooltip.innerHTML = `<div class="tt-price">${fmt.format(p.price)}</div><div class="tt-date">${dateFull(new Date(p.t))}</div>`;
      const tw = tooltip.offsetWidth;
      const clampedX = Math.max(tw / 2 + 6, Math.min(window.innerWidth - tw / 2 - 6, px));
      tooltip.style.left = `${clampedX}px`;
      tooltip.style.top = `${py}px`;
    }
    function end() { hoverG.style.opacity = "0"; tooltip.hidden = true; }

    wrap.addEventListener("pointermove", (e) => { e.preventDefault(); move(e.clientX); });
    wrap.addEventListener("pointerdown", (e) => move(e.clientX));
    wrap.addEventListener("pointerleave", end);
    wrap.addEventListener("pointercancel", end);
  }

  /* ---------------- Helpers ---------------- */
  function dateShort(d) { return d.toLocaleDateString(undefined, { month: "short", day: "numeric" }); }
  function dateFull(d) { return d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
  function escapeHtml(s) {
    return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
  }

  /* ---------------- Recent + suggestions ---------------- */
  const DEFAULT_SUGGESTS = ["AirPods Pro", "PlayStation 5", "MacBook Air", "Nintendo Switch", "Dyson V15"];
  function getRecent() {
    try { return JSON.parse(localStorage.getItem("tracer-recent") || "[]"); } catch { return []; }
  }
  function pushRecent(q) {
    const norm = q.trim();
    let list = getRecent().filter((x) => x.toLowerCase() !== norm.toLowerCase());
    list.unshift(norm);
    list = list.slice(0, 5);
    localStorage.setItem("tracer-recent", JSON.stringify(list));
    renderSuggests();
  }
  function renderSuggests() {
    const box = $("#suggests");
    const recent = getRecent();
    const items = recent.length ? recent : DEFAULT_SUGGESTS;
    const label = recent.length ? "Recent" : "Try";
    box.innerHTML = `<span class="chip" style="pointer-events:none;color:var(--text-3);border-color:transparent;background:transparent;padding-left:0">${label}</span>` +
      items.map((x) => `<button class="chip" type="button">${escapeHtml(x)}</button>`).join("");
    box.querySelectorAll("button.chip").forEach((b) =>
      b.addEventListener("click", () => { input.value = b.textContent; submit(b.textContent); }));
  }

  /* ---------------- Form ---------------- */
  const form = $("#searchForm");
  const input = $("#searchInput");
  function submit(q) {
    const query = (q ?? input.value).trim();
    if (!query) { input.focus(); return; }
    input.blur();
    render(query);
  }
  form.addEventListener("submit", (e) => { e.preventDefault(); submit(); });

  // deep link: #AirPods%20Pro
  function fromHash() {
    const h = decodeURIComponent(location.hash.replace(/^#/, "")).trim();
    if (h) { input.value = h; render(h); }
  }
  window.addEventListener("hashchange", () => {
    const h = decodeURIComponent(location.hash.replace(/^#/, "")).trim();
    if (h && (!current || current.query !== h)) { input.value = h; render(h); }
  });

  renderSuggests();
  fromHash();

  /* ---------------- PWA: service worker + install ---------------- */
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", () =>
      navigator.serviceWorker.register("./service-worker.js").catch(() => {}));
  }

  let deferredPrompt = null;
  window.addEventListener("beforeinstallprompt", (e) => {
    e.preventDefault();
    deferredPrompt = e;
    if (sessionStorage.getItem("tracer-install-dismissed")) return;
    showInstallToast();
  });

  function showInstallToast() {
    const toast = document.createElement("div");
    toast.className = "toast";
    toast.innerHTML = `<p>Install Tracer for one-tap access</p>
      <button class="install-btn" type="button">Install</button>
      <button class="dismiss" type="button" aria-label="Dismiss">×</button>`;
    document.body.appendChild(toast);
    requestAnimationFrame(() => toast.classList.add("show"));
    const close = () => { toast.classList.remove("show"); setTimeout(() => toast.remove(), 500); };
    toast.querySelector(".install-btn").addEventListener("click", async () => {
      close();
      if (deferredPrompt) { deferredPrompt.prompt(); deferredPrompt = null; }
    });
    toast.querySelector(".dismiss").addEventListener("click", () => {
      sessionStorage.setItem("tracer-install-dismissed", "1"); close();
    });
  }
})();
